version: 2.1
orbs:
  # "cypress-io/cypress@1" installs the latest published
  # version "1.x.y" of the orb. We recommend you then use
  # the strict explicit version "cypress-io/cypress@1.x.y"
  # to lock the version and prevent unexpected CI changes
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
     - cypress/install:
          build: 'npm run build' # run a custom app build step
      - cypress/run: # "run" job comes from "cypress" orb
          requires:
            - cypress/install
          yarn: true
          start: 'npm start' # start server before running tests